# docker-compose.yml
version: '3.8'

services:
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  # Next.js Application Container (includes both backend and frontend)
  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - CHOKIDAR_USEPOLLING=true
      - NEXT_PUBLIC_SUPABASE_URL=${NEXT_PUBLIC_SUPABASE_URL}
      - NEXT_PUBLIC_SUPABASE_ANON_KEY=${NEXT_PUBLIC_SUPABASE_ANON_KEY}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - redis
      - supabase-db
      - supabase-gotrue
      - supabase-realtime
    restart: always
    volumes:
      - ./:/app

  worker:
    build:
      context: .
      dockerfile: Dockerfile.worker
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - SUPABASE_URL=${SUPABASE_URL}
      - SUPABASE_KEY=${SUPABASE_KEY}
    depends_on:
      - redis
      - supabase-db
    volumes:
      - ./:/worker

  supabase-db:
    image: supabase/postgres:15.8.1.047
    command: postgres -c config_file=/etc/postgresql/postgresql.conf # Required for versions 14.1.0 and beyond
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - supabase-data:/var/lib/postgresql/data

  supabase-gotrue:
    image: supabase/gotrue:latest
    environment:
      # Configure GoTrue to connect to the Postgres database
      GOTRUE_DB_DRIVER: postgres
      GOTRUE_DB_DATABASE_URL: postgres://postgres:postgres@supabase-db:5432/postgres
      GOTRUE_JWT_SECRET: your_jwt_secret # Change this secret as needed
      GOTRUE_SITE_URL: http://localhost:3000
    ports:
      - "9999:9999"
    depends_on:
      - supabase-db

  supabase-realtime:
    image: supabase/realtime:latest
    environment:
      DB_HOST: supabase-db
      DB_PORT: "5432"
      DB_USER: postgres
      DB_PASSWORD: postgres
    ports:
      - "4000:4000"
    depends_on:
      - supabase-db

volumes:
  redis-data:
  supabase-data:
