# Dockerfile.worker

FROM node:20.11.1
WORKDIR /worker


COPY package*.json ./
RUN npm install --legacy-peer-deps

COPY . .

# Install nodemon globally for hot reload
RUN npm install -g nodemon

# Run worker with nodemon for hot reload
CMD ["nodemon", "workers/worker.js"]
